### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Nef1k** [Nef1k/CommandSystem#3]
Хз почему, после запуска не происходит ничего. Совсем. Программа запускается и работает... В консоль ничего не выдаёт. Завершается только принудительно

**Comment by Nef1k** [comment]
Зацикливается на Parser.parseCommand

**Comment by Zzzkvidi4** [comment]
Хз... У меня она вообще отказывается запускаться, ибо ей не нравятся некоторые файлы вообще...

**Comment by Zzzkvidi4** [comment]
Ты видел, я еще одну версию выложил?

**Comment by Nef1k** [comment]
Обновил, но ошибку это не исправило

**Comment by Nef1k** [comment]
Какие ей файлы не нравятся?

**Comment by Zzzkvidi4** [comment]
Обновил файлы, попробуй еще раз. ParamList и CommandManager

**Comment by Nef1k** [comment]
Fixed
