### ISSUE TITLE
Тримы не тримают

### ISSUE THREAD

**Issue by Nef1k** [Nef1k/CommandSystem#6]
cmd_text.trim(); выдаёт подсказку "result is inored" или что-то в этом роде.
Надо так: cmd_text=cmd_text.trim();

**Comment by Zzzkvidi4** [comment]
О как...

**Comment by Zzzkvidi4** [comment]
Слушай, посмотри еще на список параметров, ибо там тогда тоже могут быть косяки)

**Comment by Zzzkvidi4** [comment]
В смысле,как оно парсится

**Comment by Nef1k** [comment]
Список параметров где? ._.

**Comment by Zzzkvidi4** [comment]
params в парсере

**Comment by Zzzkvidi4** [comment]
А тримы теперь тримают... К сожалению, забыл это закоммитить, т.к. случайно вставил это во время рефакторинга.
