### ISSUE TITLE
Рефакторинг парсера

### ISSUE THREAD

**Issue by Nef1k** [Nef1k/CommandSystem#9]
Ну тут без комментариев...

**Comment by Nef1k** [comment]
ParamParse вроде можно ещё сильнее раздербанить

**Comment by Zzzkvidi4** [comment]
Ты же говорил commit'ить почти все атомарные операции) Я и делаю больше))

**Comment by Nef1k** [comment]
А, да. Сорян. Тогда отпишись, как закончишь.

**Comment by Zzzkvidi4** [comment]
Посмотри сейчас, надо ли еще дробить?)
